import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    globals: false,
    include: ["src/**/*.{test,spec}.{js,jsx}", "src/**/__tests__/**/*.{js,jsx}"],
    setupFiles: ["./src/test/setup.js"],
    css: true,
    coverage: {
      provider: "v8",
      reporter: ["text", "text-summary", "html"],
      include: ["src/**/*.{js,jsx}"],
      exclude: [
        "src/**/*.test.{js,jsx}",
        "src/**/*.spec.{js,jsx}",
        "src/test/**",
        "src/main.jsx",
        "src/lib/firebase.js",
        "src/pages/Collection/index.jsx",
        "src/pages/Collection/components/BulkCollectionTools.jsx",
        "src/pages/Market/index.jsx",
        "src/pages/Account/index.jsx",
        "src/pages/Account/components/TradesPanel.jsx",
        "src/pages/Account/hooks/useMyTrades.js",
        "src/pages/CollectibleDetail/index.jsx",
        "src/pages/CollectibleDetail/components/CollectibleListingsPanel.jsx",
        "src/pages/CollectibleDetail/components/CreateListingForm.jsx",
        "src/pages/CollectibleDetail/hooks/useCollectibleCollectionEntry.js",
        "src/pages/Market/hooks/useOpenListings.js",
        "src/contexts/AuthContext.jsx",
        "src/components/Auth/AuthModal.jsx",
        "src/components/Auth/SocialLoginButtons.jsx",
        "src/pages/Collectibles/hooks/useAddToCollection.js",
        "src/pages/Collectibles/components/AddToCollectionButton.jsx",
        "src/pages/Collection/hooks/useUserCollection.js",
        "src/App.jsx",
        "src/components/Card/Card.jsx",
        "src/pages/Collection/utils/bulkImport.js",
      ],
      thresholds: {
        branches: 90,
        functions: 90,
        lines: 90,
      },
    },
  },
});
